name: "Build & Test"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test:
    name: "Build & Test"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [8, 11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build & Test
        run: |
          mvn clean cobertura:cobertura
          bash <(curl -s https://codecov.io/bash)
          mvn test
